export const patterns_order = [
  "1-2-3",
  "1-2-3-4",
  "180-degree kickback",
  "135-degree MWSS-to-G",
  "101",
  "Achims p4",
  "Achims p8",
  "blinker",
  "acorn",
  "A for all",
  "airforce",
  "almosymmetric",
  "aVerage",
  "B29",
  "babbling brook",
  "baker",
  "banana spark",
  "beacon",
  "bent keys",
  "B-heptomino",
  "bipole",
  "biting off more than they can chew",
  "blinker pull",
  "blinkers bit pole",
  "blonker",
  "bookend",
  "boss",
  "bunnies",
  "burloaferimeter",
  "candlefrobra",
  "chicken wire",
  "clearance",
  "clock",
  "cousins",
  "crowd",
  "crystal",
  "cuphook",
  "dinner table",
  "double block reaction",
  "double caterer",
  "double ewe",
  "dove",

  "component",
  "biclock",
  "119P4H1V0",
  "25P3H1V0.1",
  "25P3H1V0.2",
  "30P5H2V0",
  "44P5H2V0",
  "crown",
  "4 boats",
  "60P5H2V0",
  "70P5H2V0",
  "AK47 reaction",
  "ants",
  "anvil",
  "bakers dozen",
  "beacon maker",
  "BFx59H",
  "block and glider",
  "blom",
  "bottle",
  "brain",
  "cover",
  "buckaroo",
  "bun",
  "butterfly",
  "by flops",
  "candelabra",
  "cap",
  "caterer",
  "chemist",
  "C-heptomino",
  "cis-beacon on anvil",
  "cis-beacon on table",
  "clock II",
  "Coe ship",
  "Coes p8",
  "colour of a glider",
  "conduit",
  "confused eaters",
  "converter",
  "dart",
  "diamond ring",
  "diehard",
  "dock",

  "4-8-12 diamond",
  "58P5H1V1",
  "67P5H1V1",
  "7x9 eater",
  "86P5H1V1",
  "Achims p16",
  "almost knightship",
  "B-52 bomber",
  "B60",
  "backrake",
  "barbershop",
  "bi-block fuse",
  "big glider",
  "blinker puffer",
  "blocker",
  "block pull",
  "block pusher",
  "boat-bit",
  "boat maker",
  "BRx46B",
  "bullet heptomino",
  "Canada goose",
  "carnival shuttle",
  "CC semi-cenark",
  "century",
  "Cheshire cat",
  "crane",
  "cross",
  "demultiplexer",
  "diuresis",
  "duoplet",

  "2c;3 wire",
  "(23,5)c;79 Herschel climber",
  "2-glider mess",
  "Achims p144",
  "2-engine Cordership",
  "56P6H1V0",
  "45-degree MWSS-to-G",
  "4g-to-5g reaction",
  "60P312",
  "92P156",
  "AK94 gun",
  "ark",
  "arm",
  "beehive stopper",
  "Beluchenkos p37",
  "Beluchenkos p51",
  "blinker ship",
  "boojum reflector",
  "Bx125",
  "Bx222",
  "Callahan G-to-H",
  "Caterpillar",
  "cauldron",
  "CC semi-Snark",
  "century-to-glider converter",
  "CP semi-cenark",
  "CP semi-Snark",
  "dragon",
];

export const patterns = {};
